---

- hosts: all
  become: true
  tasks:

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Clean up obsolete packages
      apt:
        autoremove: yes
        autoclean: yes
